env:
  global:
    - DISPLAY=":99.0"
notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
addons:
  apt:
    packages:
      - at-spi2-core
      - dbus-x11
#      - python-blockdiag
      - python-pip
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem update bundler
  - sudo -H pip install blockdiag
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - dbus-launch bundle exec rake
after_script:
  - sh -e /etc/init.d/xvfb stop
